#!/usr/bin/env Rscript

root <- normalizePath(file.path(getwd(), "TMEM158_CaUPR_ESCC"), mustWork = TRUE)
log_file <- file.path(root, "logs", "run_all.log")
dir.create(dirname(log_file), showWarnings = FALSE, recursive = TRUE)

write_log <- function(msg) {
  line <- sprintf("[%s] %s", format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z"), msg)
  cat(line, "\n")
  cat(line, "\n", file = log_file, append = TRUE)
}

write_log("Starting TMEM158 Ca2/UPR ESCC public-data branch")
script <- file.path(root, "03_scripts", "R", "run_tmem158_caupr_primary_evidence.R")
status <- system2("Rscript", script)
write_log(sprintf("run_tmem158_caupr_primary_evidence.R exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "R", "run_tmem158_ecology_state_subtyping.R")
status <- system2("Rscript", script)
write_log(sprintf("run_tmem158_ecology_state_subtyping.R exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "R", "run_tmem158_multiomics_regulation.R")
status <- system2("Rscript", script)
write_log(sprintf("run_tmem158_multiomics_regulation.R exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "R", "run_tmem158_public_protein_context.R")
status <- system2("Rscript", script)
write_log(sprintf("run_tmem158_public_protein_context.R exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "Python", "run_tmem158_alphafold_topology_context.py")
status <- system2("python3", script)
write_log(sprintf("run_tmem158_alphafold_topology_context.py exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "Python", "build_tmem158_protein_topology_claim_audit.py")
status <- system2("python3", script)
write_log(sprintf("build_tmem158_protein_topology_claim_audit.py exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "R", "run_tmem158_tac_high_specificity.R")
status <- system2("Rscript", script)
write_log(sprintf("run_tmem158_tac_high_specificity.R exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "R", "run_tmem158_tac_high_transcriptome_program.R")
status <- system2("Rscript", script)
write_log(sprintf("run_tmem158_tac_high_transcriptome_program.R exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "R", "run_tmem158_stromal_adjusted_tac_program.R")
status <- system2("Rscript", script)
write_log(sprintf("run_tmem158_stromal_adjusted_tac_program.R exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "R", "run_tmem158_gse53625_external_clinical_validation.R")
status <- system2("Rscript", script)
write_log(sprintf("run_tmem158_gse53625_external_clinical_validation.R exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "R", "run_tmem158_tac_high_scrna_signature_localization.R")
status <- system2("Rscript", script)
write_log(sprintf("run_tmem158_tac_high_scrna_signature_localization.R exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "R", "run_tmem158_tac_high_caf_epi_lr_bridge.R")
status <- system2("Rscript", script)
write_log(sprintf("run_tmem158_tac_high_caf_epi_lr_bridge.R exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "Python", "build_tmem158_structural_followup_prioritization.py")
status <- system2("python3", script)
write_log(sprintf("build_tmem158_structural_followup_prioritization.py exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "Python", "build_tmem158_lr_compartment_expression_audit.py")
status <- system2("python3", script)
write_log(sprintf("build_tmem158_lr_compartment_expression_audit.py exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "R", "run_tmem158_gse221561_tac_context_validation.R")
status <- system2("Rscript", script)
write_log(sprintf("run_tmem158_gse221561_tac_context_validation.R exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "R", "run_tmem158_spatial_progression_context.R")
status <- system2("Rscript", script)
write_log(sprintf("run_tmem158_spatial_progression_context.R exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "Python", "finalize_tmem158_literature_gate.py")
status <- system2("python3", script)
write_log(sprintf("finalize_tmem158_literature_gate.py exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "Python", "scan_tmem158_downloaded_fulltexts.py")
status <- system2("python3", script)
write_log(sprintf("scan_tmem158_downloaded_fulltexts.py exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "Python", "build_tmem158_submission_readiness_package.py")
status <- system2("python3", script)
write_log(sprintf("build_tmem158_submission_readiness_package.py exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "Python", "run_claim_boundary_text_audit.py")
status <- system2("python3", script)
write_log(sprintf("run_claim_boundary_text_audit.py exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "Python", "build_reviewer_risk_response_pack.py")
status <- system2("python3", script)
write_log(sprintf("build_reviewer_risk_response_pack.py exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "Python", "build_submission_system_fields_pack.py")
status <- system2("python3", script)
write_log(sprintf("build_submission_system_fields_pack.py exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "Python", "build_scientific_reports_docx.py")
status <- system2("python3", script)
write_log(sprintf("build_scientific_reports_docx.py exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "Python", "render_scientific_reports_docx_qa.py")
status <- system2("python3", script)
write_log(sprintf("render_scientific_reports_docx_qa.py exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "Python", "build_scientific_reports_official_policy_audit.py")
status <- system2("python3", script)
write_log(sprintf("build_scientific_reports_official_policy_audit.py exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "Python", "build_target_journal_live_policy_refresh.py")
status <- system2("python3", script)
write_log(sprintf("build_target_journal_live_policy_refresh.py exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "Python", "run_manuscript_numeric_consistency_audit.py")
status <- system2("python3", script)
write_log(sprintf("run_manuscript_numeric_consistency_audit.py exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "Python", "run_scientific_reports_citation_coverage_audit.py")
status <- system2("python3", script)
write_log(sprintf("run_scientific_reports_citation_coverage_audit.py exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "Python", "build_submission_archive_package.py")
status <- system2("python3", script)
write_log(sprintf("build_submission_archive_package.py exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "Python", "build_final_sci_submission_gap_audit.py")
status <- system2("python3", script)
write_log(sprintf("build_final_sci_submission_gap_audit.py exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "Python", "build_final_author_submission_handoff.py")
status <- system2("python3", script)
write_log(sprintf("build_final_author_submission_handoff.py exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
script <- file.path(root, "03_scripts", "Python", "build_scientific_reports_submission_bundle.py")
status <- system2("python3", script)
write_log(sprintf("build_scientific_reports_submission_bundle.py exit status: %s", status))
if (!identical(status, 0L)) quit(status = status)
write_log("TMEM158 branch run completed")
